FROM pytorch/pytorch:1.12.1-cuda11.3-cudnn8-runtime
RUN pip install tensorboard
RUN pip install matplotlib
RUN pip install opencv-python-headless
RUN pip install albumentations
RUN pip install yacs
RUN pip install timm

WORKDIR /home2/johannae/semi-lines/UniMatch