datasets:
    name: 'wireframe'
    input_size: 512

model:
    model_name: 'mobilev2_mlsd'
    with_deconv: True

# arguments for dataset
unimatch:
    dataset: wireframe
    nclass: 16 #?
    crop_size: 512 #321 # 513 # 801
    data_root: /home2/johannae/semi-lines/UniMatch/data/wireframe_raw
    save_images: /home2/johannae/semi-lines/UniMatch/out
    conf_thresh: 0.95


train:
    save_dir: './workdir/models/trees/'
    img_dir:  "./data/wireframe_raw/images/"
    label_fn: "./data/wireframe_raw/train.json"
    num_train_epochs: 200
    batch_size: 2 #2 #12 # 48
    learning_rate: 0.0001 #0.001
    use_step_lr_policy: True
    weight_decay: 0.000001
    load_from: ""
    warmup_steps: 100
    milestones: [ 50, 100, 150 ]
    milestones_in_epo: True
    lr_decay_gamma: 0.2

    data_cache_dir: "./data/wireframe_cache/"
    with_cache: False
    cache_to_mem: False

val:
    img_dir: "./data/wireframe_raw/images/"
    label_fn: "./data/wireframe_raw/train.json"
    batch_size: 2
    val_after_epoch: 50

test:
    img_dir: "./data/wireframe_raw/images/"
    label_fn: "./data/wireframe_raw/valid.json"

wireframe:
    img_dir: "./data/wireframe_raw/images/"
    label_fn: "./data/wireframe_raw/valid.json"

test_finn:
    img_dir: "./data/FinnForest/rgb/val/"
    label_fn: "./data/FinnForest/annos_val_finnwoods.json"

loss:
    loss_weight_dict_list: [ { 'tp_center_loss': 10.0,'sol_center_loss': 1.0,'tp_match_loss':1.0 } ]

    with_match_loss: True
    with_focal_loss: True
    focal_loss_level: 0
    with_sol_loss: True
    match_sap_thresh: 5.0

decode:
    score_thresh: 0.05 #0.1 #0.08 # 0.05
    len_thresh: 5
    top_k: 500
    sap_thresh: 10 #10